name: vue-ai-chatbot-cuda

services:
  backend:
    build: 
      context: ./services/backend
      dockerfile: Dockerfile.cuda
    ports:
      - 5051:5051
    volumes:
      - ./services/backend:/app
      - huggingface_hub_cache:/root/.cache/huggingface/hub
    command: uvicorn src.main:app --host 0.0.0.0 --port 5051
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: always

  frontend:
    build: ./services/frontend
    volumes:
      - ./services/frontend:/app
      - node_modules:/app/node_modules
    ports:
      - 8081:8081
    restart: always

volumes:
  huggingface_hub_cache:
  node_modules:
