version: '3.8'

services:

  backend:
    build: ./services/backend
    ports:
      - 5050:5050
    volumes:
      - ./services/backend:/app
    command: uvicorn src.main:app --host 0.0.0.0 --port 5050

  frontend:
    build: ./services/frontend
    volumes:
      - './services/frontend:/app'
      - '/app/node_modules'
    ports:
      - 8080:8080