name: vue-ai-chatbot

services:
  backend:
    build:
      context: ./services/backend
      dockerfile: Dockerfile
    ports:
      - 5051:5051
    volumes:
      - ./services/backend:/app
      - pip_cache:/root/.cache/pip
      - huggingface_hub_cache:/root/.cache/huggingface/hub
    command: uvicorn src.main:app --host 0.0.0.0 --port 5051
    restart: always

  frontend:
    build: ./services/frontend
    volumes:
      - ./services/frontend:/app
      - node_modules:/app/node_modules
    ports:
      - 8081:8081
    restart: always