name: vue-ai-chatbot

services:
  backend:
    build:
      context: ./services/backend
      dockerfile: Dockerfile.cpu
    ports:
      - 5051:5051
    volumes:
      - ./services/backend:/app
      - huggingface_hub_cache:/root/.cache/huggingface/hub
    restart: always

  frontend:
    build: ./services/frontend
    volumes:
      - ./services/frontend:/app
      - node_modules:/app/node_modules
    ports:
      - 8081:8081
    restart: always

volumes:
  huggingface_hub_cache:
  node_modules: