FROM python:3.12.8-bookworm

WORKDIR /app

ENV PATH="${PATH}:/root/.local/bin"
ENV PYTHONPATH=.

COPY requirements.cuda.txt .

RUN --mount=type=cache,target=/root/.cache/pip pip install -r requirements.cuda.txt